
name: Build and Publish

on:
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'


      - name: Restore dependencies
        run: dotnet restore src

      - name: Build project
        run: dotnet build src --configuration Release
        
      - name: Run tests
        run: dotnet test src --no-build --verbosity debug --collect:"XPlat Code Coverage" --logger trx --results-directory coverage

      - name: Code Coverage Summary Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: 'coverage/*/coverage.cobertura.xml'
          badge: true
          format: 'markdown'
          output: 'both'

      - name: Add Coverage PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request'
        with:
          recreate: true
          path: code-coverage-results.md

      - name: Write to Job Summary
        run: cat code-coverage-results.md >> $GITHUB_STEP_SUMMARY
              
      #- name: Publish to NuGet
      #  run: dotnet nuget push <path-to-nupkg> --source <nuget-org-source> --api-key ${{ secrets.NUGET_API_KEY }}
